name: Build and Release APK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    permissions: 
      contents: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Decode Keystore
        run: |
          mkdir -p gpslogger/keystore
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > gpslogger/keystore/your_signing_keystore.jks
        shell: bash

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Copy and rename the APK
        run: ./gradlew copyFinalAPK

      - name: Get APK reference
        id: references
        run: |
          APK_FILE_NAME=$(find gpslogger/ -maxdepth 1 -name "gpslogger-*.apk" -print -quit | xargs basename)
          echo "APK_FILE_NAME=$APK_FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: Checksum the APK
        run: |
          cd gpslogger 
          sha256sum ${{ steps.references.outputs.APK_FILE_NAME }} > ${{ steps.references.outputs.APK_FILE_NAME }}.SHA256

      - name: Cosign Attestation of the APK
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-path: gpslogger/gpslogger-*.apk

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref, '-rc') && startsWith(github.ref, 'refs/tags/') }}
          make_latest: true
          body: |
            GPSLogger Local Build
            
            Checksum SHA256:
            ```
            $(cat gpslogger/*.SHA256)
            ```
          files: |
            gpslogger/gpslogger-*.apk
            gpslogger/gpslogger-*.apk.SHA256
